### ISSUE TITLE
데이터베이스 설계

### ISSUE THREAD

**Issue by rojiwon123** [zipzoong/zipzoong-backend-legacy-#3]
- ERD 작성

**Comment by industriously** [comment]
# 회원 인증/관리 ERD
<img width="630" alt="스크린샷 2023-04-15 오후 8 55 18" src="https://user-images.githubusercontent.com/116284195/232218684-b31aadb5-1884-48c5-83da-f3b1a2389383.png">

**Comment by industriously** [comment]
# 비즈니스 전문 분야 ERD
<img width="1079" alt="스크린샷 2023-04-15 오후 9 16 05" src="https://user-images.githubusercontent.com/116284195/232222932-3595da98-af43-4053-82ef-2ceec8f71536.png">

**Comment by industriously** [comment]
# 홈케어 회사 자체리뷰 이미지 ERD
<img width="583" alt="스크린샷 2023-04-15 오후 9 24 16" src="https://user-images.githubusercontent.com/116284195/232223368-0a45c701-5f39-4e04-ae31-c31438f45e49.png">

**Comment by industriously** [comment]
# 부동산 매물 ERD
<img width="422" alt="스크린샷 2023-04-15 오후 9 29 13" src="https://user-images.githubusercontent.com/116284195/232223615-893a9bcd-69d9-4351-a6a0-0acdfebf3cab.png">

**Comment by industriously** [comment]
# 비즈니스 사용자 리뷰/평점 ERD
<img width="939" alt="스크린샷 2023-04-15 오후 9 40 09" src="https://user-images.githubusercontent.com/116284195/232224194-014ec19c-6c95-433c-9ebe-04ba9f051dca.png">

**Comment by rojiwon123** [comment]
# 게시판 시스템 ERD
<img width="658" alt="스크린샷 2023-04-15 오후 9 58 06" src="https://user-images.githubusercontent.com/116284195/232225119-4955d0ba-a764-4423-9a0c-98b31f8cadcb.png">

**Comment by industriously** [comment]
회원 인증/관리 시스템 최종
<img width="981" alt="스크린샷 2023-04-27 오후 9 57 15" src="https://user-images.githubusercontent.com/116284195/234868802-76965d38-16b4-4a7a-8134-4e749294809b.png">
